name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: cd client && npm install
      - name: lint code
        run: npm run lint
      - name: run tests
        run: npm run test
      - name: create badge
        run: npm run coverage:badge
      - name: Commit changes
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { Octokit } = require('@octokit/rest');
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            const content = fs.readFileSync('README.md', 'utf8');
            const { data } = await octokit.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md',
              ref: context.sha,
            });
            await octokit.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md',
              message: 'Update README.md',
              content: Buffer.from(content).toString('base64'),
              sha: data.sha,
            });
